language: android

android:
  components:
    - tools
    - build-tools-25.0.0
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - android-25
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator

  - adb shell echo Turn off animations because espresso is broken by design.
  - adb shell settings put global window_animation_scale 0
  - adb shell settings put global transition_animation_scale 0
  - adb shell settings put global animator_duration_scale 0

  - adb shell echo Hit the menu key because all the other Travis builds seem to do so.
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build check connectedCheck

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "LnEHmq5BKRzXvuWJwOjZsIW0gNTr6d/JT1dOuYLsKYmGQ+0MLbjoB1J1AIpZ5X1qcDDUbPomQ2YDYvi+cavjk6FMccyKxnnC5sqjUgTnkHOnVzteGFP+0TYT3JZnjFrzp6mxNXG2vPeuyIAdDZRTogEOe83nfFRvytj6VGK/seI="
    - secure: "qdCwZom4m109rrqm80N/Q+JTYob5WubDnPVKJlXoMIzh+ppq6XWiqKsBUypzn9sSEVHuYSQAzeUqyp3ET0E/sNyvnOe9cRQEs7aMjYSXw5XUYrsPT10HbAStmqPeGp6X+LuOr+jmfPQyyKeZGBOLq3Trb1yRGlrwMQhE6BFbX8g="

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
